FROM rabbitmq:3.12-management
COPY /client/rabbitmq.conf /etc/rabbitmq
COPY /client/definitions.json /etc/rabbitmq
COPY /client/advanced.config /etc/rabbitmq
COPY /client/ca.bundle /etc/rabbitmq
COPY /client/client_certificate.pem /etc/rabbitmq
COPY /client/private_key.pem /etc/rabbitmq
RUN chmod 664 /etc/rabbitmq/ca.bundle
RUN chmod 664 /etc/rabbitmq/client_certificate.pem
RUN chmod 664 /etc/rabbitmq/private_key.pem
RUN rabbitmq-plugins enable --offline rabbitmq_shovel
RUN rabbitmq-plugins enable --offline rabbitmq_shovel_management

