# version: '3.8', not needed version
services:
  grafana:
    # https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/
    image: grafana/grafana-oss
    # build:
    #  context: .
    #  dockerfile: Dockerfile.grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
      - GF_SECURITY_ADMIN_USER=linuxuser
      - GF_SECURITY_ADMIN_PASSWORD=Minime789gotooslo
      # https://grafana.com/api/plugins
      # - GF_INSTALL_PLUGINS=grafana-mongodb-datasource
    ports:
      - '3000:3000'
    networks:
      - static_network
    volumes:
      - vol_grafana:/var/lib/grafana
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=adminuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=myOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=myBucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=randomTokenValue
    ports:
      - 8086:8086
    networks:
      static_network:
        ipv4_address: 172.27.0.2
    volumes:
      - vol_influxdb:/var/lib/influxd


networks:
  static_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/28
          gateway: 172.27.0.1

volumes:
  vol_grafana:
  vol_influxdb: