services:
    python-boilerplate:
        build: .
        volumes:
            - .:/code
            - log:/user/src/appdir
        networks:
            - app_network

networks:
    app_network:
volumes:
    log:


# remove all images
# docker rmi -f $(docker images -aq)

# remove all volumes
# docker volume rm $(docker volume ls -qf dangling=true)