version: '3'

services:
# rabbitmq with a static host name
  rmq-app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: rmq4.cloud
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - vol_rabbitmq_data:/var/lib/rabbitmq
# portainer for view containers
  portainer:
    image: portainer/portainer-ce
    # command: https://gist.github.com/deviantony/62c009b41bde5e078b1a7de9f11f5e55
    restart: always
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_portainer_data:/data

# So here we've assigned the 'default' network for this stack to be net_messaging
# This applies to all the services which do not have their own networks: variable
networks:
  default:
    name: net_messaging
    ipam: 
      config:
        - subnet: 172.50.0.0/24

volumes:
  vol_rabbitmq_data:
  vol_portainer_data:

# cd dir
# docker compose up -d
# http://public-ip:15672
# https://public-ip:9443

# Edit Docker file?
# docker rmi -f $(docker images -aq)

# Maybe you need to rm volumes also if container name is changed or hostname
# docker volume rm $(docker volume ls -qf dangling=true)
