version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 750m
    # command: https://gist.github.com/deviantony/62c009b41bde5e078b1a7de9f11f5e55
    restart: always
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_portainer_data:/data

volumes:
  vol_portainer_data:

# open inbound NSG
# no http management, , refresh and clear cache
# cd dir
# docker compose up -d
# https://public-ip:9443

# remove all images
# docker rmi -f $(docker images -aq)

# Maybe you need to rm volumes also if container name is changed or hostname
# docker volume rm $(docker volume ls -qf dangling=true)