FROM rabbitmq:3.13-management
COPY /server/rabbitmq.conf /etc/rabbitmq
COPY /server/definitions.json /etc/rabbitmq
RUN rabbitmq-plugins enable --offline rabbitmq_shovel
RUN rabbitmq-plugins enable --offline rabbitmq_shovel_management

