FROM rabbitmq:3.13-management
COPY /client/rabbitmq.conf /etc/rabbitmq
COPY /client/definitions.json /etc/rabbitmq
COPY /client/advanced.config /etc/rabbitmq
RUN rabbitmq-plugins enable --offline rabbitmq_shovel
RUN rabbitmq-plugins enable --offline rabbitmq_shovel_management

