# version: '3'
# `version` is obsolete
services:
# rabbitmq with a static host name
  rmq-app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: rmq4.cloud
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500m
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net_messaging
    volumes:
      - vol_rabbitmq_data:/var/lib/rabbitmq
      
networks:
  net_messaging:

volumes:
  vol_rabbitmq_data:


# https://follow-e-lo.com/2024/07/10/docker-rabbitmq-2/

# open inbound NSG
# no http management, , refresh and clear cache
# cd dir
# docker compose up -d
# http://public-ip:15672

# Edit Docker file?
# docker compose up -d --build
# or
# docker compose

# remove all images
# docker rmi -f $(docker images -aq)

# remove all volumes
# docker volume rm $(docker volume ls -qf dangling=true)
