version: '3' 

services:

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
    environment:
      - DB_SERVER_HOST=zabbix-database
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix  
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    depends_on:
      - zabbix-database

  zabbix-database:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zabbix_db:/var/lib/mysql

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.0-latest
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - ZBX_HOSTNAME=Zabbix Agent 
      - ZBX_SERVER_HOST=zabbix-server