version: '3.1'

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-6.0-latest
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
    depends_on:
      - mysql-server

  mysql-server:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-6.0-latest
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_HOSTNAME=Zabbix Server
    depends_on:
      - zabbix-server
      
volumes:
  mysql-data: