services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - vol_grafana_data:/var/lib/grafana
networks:
  net_grafana_mysql:
    # is default
    # driver: bridge

volumes:
  vol_grafana_data:


