az container create --resource-group
                    [--acr-identity]
                    [--add-capabilities]
                    [--allow-escalation]
                    [--assign-identity]
                    [--azure-file-volume-account-key]
                    [--azure-file-volume-account-name]
                    [--azure-file-volume-mount-path]
                    [--azure-file-volume-share-name]
                    [--cce-policy]
                    [--command-line]
                    [--cpu]
                    [--dns-name-label]
                    [--drop-capabilities]
                    [--environment-variables]
                    [--file]
                    [--gitrepo-dir]
                    [--gitrepo-mount-path]
                    [--gitrepo-revision]
                    [--gitrepo-url]
                    [--image]
                    [--ip-address {Private, Public}]
                    [--location]
                    [--log-analytics-workspace]
                    [--log-analytics-workspace-key]
                    [--memory]
                    [--name]
                    [--no-wait]
                    [--os-type {Linux, Windows}]
                    [--ports]
                    [--priority]
                    [--privileged]
                    [--protocol {TCP, UDP}]
                    [--registry-login-server]
                    [--registry-password]
                    [--registry-username]
                    [--restart-policy {Always, Never, OnFailure}]
                    [--role]
                    [--run-as-group]
                    [--run-as-user]
                    [--scope]
                    [--seccomp-profile]
                    [--secrets]
                    [--secrets-mount-path]
                    [--secure-environment-variables]
                    [--sku]
                    [--subnet]
                    [--subnet-address-prefix]
                    [--vnet]
                    [--vnet-address-prefix]
                    [--vnet-name]
                    [--zone]
```